### ISSUE TITLE
Jeep Uconnect Portal

### ISSUE THREAD

**Issue by Ytnom2404** [TA2k/ioBroker.fiat#4]
Hello, would it be possible to add a Jeep version? It uses same Uconnect stuff just via the uconnect Jeep portal.

Would be great if i can modify the code to login to the jeep portal :-)

With kind Regads
Michael

**Comment by TA2k** [comment]
Need credentials for add this 
contact me in the iobroker forum https://forum.iobroker.net/user/tombox

**Comment by TA2k** [comment]
I add blindly the jeep support in the github version but not tested with a vehicle

**Comment by Wildbill-Z** [comment]
@TA2k Just to tell you that it works: I own 2 Jepp (Compass PHEV 2021 and Renegade PHEV 2022) and both of them fully work in iobroker. So I think, you could close this issue.
