### ISSUE TITLE
wrong value type

### ISSUE THREAD

**Issue by Armin46** [TA2k/ioBroker.fiat#6]
Hallo, ich erhalte die folgenden Protokolleinträge .
Kannst du dir das mal anschauen und den typ ändern ? 

Vielen Dank

<html><body>

fiat.0 | 2022-11-14 22:53:42.499 | info | State  value to set for  "fiat.0.ZAREAFDNxxxxx.status.vehicleInfo.tyrePressure04.pressure.value"  has to be type "number" but received type "string"
-- | -- | -- | --
fiat.0 | 2022-11-14 22:53:42.499 | info | State  value to set for  "fiat.0.ZAREAFDNxxxxx.status.vehicleInfo.tyrePressure03.pressure.value"  has to be type "number" but received type "string"
fiat.0 | 2022-11-14 22:53:42.499 | info | State  value to set for  "fiat.0.ZAREAFDNxxxxx.status.vehicleInfo.tyrePressure02.pressure.value"  has to be type "number" but received type "string"
fiat.0 | 2022-11-14 22:53:42.498 | info | State  value to set for  "fiat.0.ZAREAFDNxxxxx.status.vehicleInfo.tyrePressure01.pressure.value"  has to be type "number" but received type "string"
fiat.0 | 2022-11-14 22:53:42.448 | info | State value to set for "fiat.0.ZAREAFDNxxxxx.location.latitude" has to be type "number" but received type "string"

</body>
</html>

**Comment by TA2k** [comment]
Werden automatisch erstellt. Sollte funktionieren wenn man die Datenpunkte manuell löscht und dann adapter Neustarten

**Comment by Armin46** [comment]
Perfekt Danke das war die Lösung. Ich dachte die Typen werden vom Adapter vorgegeben.
